### ISSUE TITLE
Flyway 4.0.2 released

### ISSUE THREAD

**Issue by msteinhoff** [dropwizard/dropwizard-flyway#11]
https://flywaydb.org/documentation/releaseNotes

Whats the update policy anyway? Update when time permits it? :D

**Comment by joschi** [comment]
> Whats the update policy anyway? Update when time permits it? :D

Exactly that.

**Comment by joschi** [comment]
Closed by 830e69d17a9cadb9413b1b3cecfb745dc8f2935d and 3cd222fa71a04f9e3ad812e23b0a833d7652475a.
