### ISSUE TITLE
Support for EnvironmentVariableSubstitutor?

### ISSUE THREAD

**Issue by lutzhorn** [dropwizard/dropwizard-flyway#17]
Dropwizard supports [sourcing of environment variables](http://www.dropwizard.io/1.1.2/docs/manual/core.html#environment-variables). Since the Flyway CLI command does not run the Application, it does not know about a configured `EnvironmentVariableSubstitutor`.

Is it possible to source environment variables to be used in the YAML configuration file when a CLI command like `db info` is issued?

**Comment by joschi** [comment]
@lutzhorn Any particular reason you've closed the issue and the PR?

**Comment by lutzhorn** [comment]
We found out that environment variables are expanded in the YAML file even without this change. So the PR is not needed, as far as I understand.

**Comment by joschi** [comment]
@lutzhorn Awesome. That would've been my question on the PR anyway. 😉
