### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by esnellman** [dropwizard/dropwizard-flyway#3]
<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-db</artifactId>
			<version>0.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.dropwizard.modules</groupId>
			<artifactId>dropwizard-flyway</artifactId>
			<version>0.8.0-1</version>
			<exclusions>
				<exclusion>
					<artifactId>dropwizard-db</artifactId>
					<groupId>io.dropwizard</groupId>
				</exclusion>
			</exclusions>
		</dependency>

Can you provide some examples of using Flyway commands in the readme?

I tried:

db info config.yml
-> invalid choice: 'config.yml' (choose from 'clean', 'info', 'init', 'migrate', 'repair', 'validate')
db config.yml info 
-> default configuration has an error:   * Unrecognized field at:
db config.yml info server
-> file not found server
server config.yml db info
-> unrecognized arguments: 'db info'

**Comment by esnellman** [comment]
db info info config.yml
works

**Comment by joschi** [comment]
This was a bug in the last release. I've fixed it and will release dropwizard-flyway 0.8.0-2.
