### ISSUE TITLE
Warning: Direct configuration of the Flyway object has been deprecated

### ISSUE THREAD

**Issue by amr** [dropwizard/dropwizard-flyway#41]
This warning is pretty many times in the logs:

`org.flywaydb.core.Flyway - Direct configuration of the Flyway object has been deprecated and will be removed in Flyway 6.0. Use Flyway.configure() instead.`

I'm using version `1.3.0-4`

**Comment by joschi** [comment]
@amr Thanks for reporting this!

The issue should be solved in dropwizard-flyway 1.3.0-5.
