### ISSUE TITLE
Plans for new release?

### ISSUE THREAD

**Issue by pogopaule** [dropwizard/dropwizard-flyway#64]
The last release has been published on 7 Jul 2018. Are there any plans to publish a new release anytime soon? I'm asking since flyway-core has been upgraded in the meantime.

**Comment by wslulciuc** [comment]
+1

**Comment by joschi** [comment]
@pogopaule @wslulciuc Thanks for your questions!

Yes, we plan to do a release soon, primarily to make it compatible with Dropwizard 2.0.0.

This being said, it's currently a matter of a lack of time, so don't hold your breath that it'll happen within the next few days.

**Comment by joschi** [comment]
@pogopaule I've just released dropwizard-flyway 1.3.0-5 and 1.3.0-6.

A version compatible with Dropwizard 2.0.x will follow soon.
