### ISSUE TITLE
ALTER COLUMN in Redshift is killing me

### ISSUE THREAD

**Issue by radifalco** [dropwizard/dropwizard-flyway#67]
I have a deploy and I can't deploy because of this issue. 
```
[Amazon](500310) Invalid operation: ALTER TABLE ALTER COLUMN cannot run inside a transaction block;
```
This requires using flyway release 6. I can't just add the dependency because a constructor has changed. How soon until a new release? Or is there some other workaround until then?

**Comment by joschi** [comment]
@radifalco Thanks for reporting this!

The issue should be fixed in dropwizard-flyway 1.3.0-5 and later.
