### ISSUE TITLE
Allow Out of Order DB Migration Configuration

### ISSUE THREAD

**Issue by ilyanep** [dropwizard/dropwizard-flyway#9]
@joschi 

We want to more or less be able to implement this procedure on our team (tl;dr version numbers are timestamps and we allow out of order migrations on dev machines to avoid branch hell): http://www.jeremyjarrell.com/using-flyway-db-with-distributed-version-control/

It looks to me like this would be accomplished by putting an option on `FlywayConfiguration` and then just setting the option in `FlywayFactory`. If that's all that's needed, I'm happy to submit a PR to do it.

**Comment by joschi** [comment]
@ilyanep A pull request implementing this feature would definitely be welcome!

**Comment by JChrist** [comment]
I believe all flyway arguments, as described [here](https://flywaydb.org/documentation/commandline/migrate) should also be configurable, not only `outOfOrder`.

The process for all arguments should be the same, i.e. adding an option on `FlywayConfiguration` and setting that option in `FlywayFactory`

**Comment by dotCipher** [comment]
Added a PR for this under #10

**Comment by JChrist** [comment]
I'm not sure if this is an issue or a "feature", but if I'm not mistaken, in CLI mode the options `outOfOrder`, `validateOnMigrate`, `cleanOnValidationError` and `baselineOnMigrate (or initOnMigrate)` will be overriden with the CLI arguments or their defaults if they are absent, as I can see in [DbMigrateCommand](https://github.com/dropwizard/dropwizard-flyway/blob/master/src/main/java/io/dropwizard/flyway/cli/DbMigrateCommand.java#L71)

**Comment by dotCipher** [comment]
True, I leave that decision up to the repo owner @joschi
